### ISSUE TITLE
Documentation: Explain RichText inline editor use

### ISSUE THREAD

**Issue by seangwright** [Kentico/ems-mvc-components#113]
### Motivation

The RichText widget is a nice tool to have in an MVC site using Page Builder.

However, the widget itself doesn't do much, it's really the inline editor that provides all the power.

While some devs might be fine using the widget directly, we have many use cases where we want to control where on a page the inline editor content is displayed on the live site.

We also want to use the inline editor in combination with other custom widgets.

This is pretty easy to accomplish but it's not clear from the documentation that this is possible or a supported use case (the wiki makes reference to this idea without explaining it).

### Proposed solution

Update the [README.md](https://github.com/Kentico/ems-mvc-components/blob/master/Kentico.InlineEditor.RichText/README.md) for the inline editor or the widget (or both) to explain more uses cases and the flexibility of these components.

### Additional context

At the bottom of this [wiki page](https://github.com/Kentico/ems-mvc-components/wiki/Customizing-the-Rich-text-editor-toolbar) is a code snippet showing how the inline editor can be used separate from the widget.

I'm happy to make a PR to update the docs if this seems like a good idea.

**Comment by OndraM-Kentico** [comment]
Hi, thank you for the feedback. Obviously the wiki page is not very verbose... we would be grateful for suggesting more real-life use cases, so feel free to draft a PR with your ideas.

**Comment by OndraM-Kentico** [comment]
@seangwright have you progressed with the PR so far? Btw, let us know if there is another issue we could address. Otherwise, I'll close this issue.

**Comment by seangwright** [comment]
I'm still planning on adding some instructions, but my free time filled up very quickly recently with clients / projects.

I'll close this and submit the PR separately.

Thanks!
