### ISSUE TITLE
RichText Inline Editor broken Hyperlink features when using inside Custom Widget

### ISSUE THREAD

**Issue by johnventions** [Kentico/ems-mvc-components#116]
### Brief bug description

I have been able to successfully include a RichText Inline Editor inside of my own MVC Widgets by using:
`Html.Kentico().RichTextEditor(nameof(MyCustomWidgetProperties.Content));`

However, you are unable to edit existing hyperlink elements inside of the RichTextEditor after they have been created (this is the same for linking to Kentico Nodes or Media files)

The editor does an API call to a `GetLinkMetaData `action, and the path includes the nameof() for the new CustomWidget. That action does not exist within our custom widget unless we create a custom widget controller and replicate the functionality.

Example failing URL:
`/cmsctx/pv/administrator/culture/en-us/wg/06ed4ce7-760e-4f06-8c8a-2c00b4991880/readonly/0/pts/637219245920948421/ea/1/h/188ce8f644a36953bb0965351e4645048158aa286deda846ef5ba346da7f3201/-/kentico.pagebuilder/widgets/en-us/Custom.MyCustomWidget/getlinkmetadata`

Can the GetLinkMetaData API call have a static route associated with the Inline Editor instead of being tied to the KenticoRichTextWidgetController ?

### Repro steps

1. Create a new Widget (MyCustomWidgetProperties.cs) containing a Content string field
2. Use the RichText Inline Editor with your custom widget view:
   `Html.Kentico().RichTextEditor(nameof(MyCustomWidgetProperties.Content));`
3. Create a page with your new widget
4. Inside the widget create a hyperlink to another Kentico node
5. Save the page
6. Attempt to edit the hyperlink target from Step 4

### Expected behavior

I expected the inline editor to work outside of the RichTextWidget MVC widget and it does _except_ for this one feature.

### Test environment

 - Chrome 54. Kentico v12.0.52

### Additional Information
The GetLinkMetaData is currently located here:
https://github.com/Kentico/ems-mvc-components/blob/master/Kentico.Widget.RichText/Controllers/KenticoRichTextWidgetController.cs

LinkMetaData route is defined as an html attribute as:
data-get-link-metadata-endpoint-url

**Comment by rpribyl** [comment]
Hi @johnventions,
did you install the RichText editor via the NuGet package (https://www.nuget.org/packages/Kentico.EMS12.MvcComponents.Widget.RichText/)? Or did you compile it yourself from this repo?
I'm asking because the NuGet package contains also the RichText Editor widget which defines the route. If you use only the inline editor itself (without the widget DLL), you have to register the route manually:
````
using Kentico.Components.Web.Mvc.InlineEditors;

routeCollection.Kentico().MapRichTextInlineEditorRoutes()
````

**Comment by johnventions** [comment]
Thanks @rpribyl - I'm using the NuGet package. 
The route works perfectly when using the RichTextWidget - no issues there.

But it does not work when using the Inline Editor inside custom widgets that are not the RichTextWidget

The meta data endpoint is defined differently for custom widgets:

#### Custom Widget Meta Endpoint

> data-get-link-metadata-endpoint-url=
> "/cmsctx/pv/administrator/culture/en-us/wg/...../-/Kentico.PageBuilder/Widgets/en-US/**Custom.MycustomWidget**/GetLinkMetadata"


#### Rich Text Widget Meta Endpoint

>  data-get-link-metadata-endpoint-url=
> "/cmsctx/pv/administrator/culture/en-us/wg/....../-/Kentico.PageBuilder/Widgets/en-US/**Kentico.Widget.RichText**/GetLinkMetadata"

So (I think) the inline editor assumes that every widget has a GetLinkMetaData action, instead of using a shared Action. Its attempting to find a MyCustomWidget controller and GetLinkMetaData action?

**Comment by rpribyl** [comment]
Hi @johnventions,
I've tested your scenario and it led to the same result as you are experiencing.
There is a bug in the inline editor in the _GetLinkMetaData_ route registration because you should not be required to implement the _GetLinkMetaData_ action in your custom widget.

Unfortunately, there is no workaround at the moment,
we'll try to address the issue as soon as possible.

**Comment by johnventions** [comment]
Thanks for confirming, @rpribyl - I'll be happy to have this working correctly in the future.

**Comment by OndraM-Kentico** [comment]
Hi @johnventions, FYI, feel free to update _Kentico.EMS12.MvcComponents.Widget.RichText_ package to the latest version (1.2.1) to fix the issue.
