### ISSUE TITLE
[Proposal] Custom Properties for Form Sections

### ISSUE THREAD

**Issue by vhugogarcia** [Kentico/ems-mvc-components#118]
### Motivation

Not all forms are just a simple array of fields. Complex forms require the ability to add Headings to outline a section of the form, for example, Billing Information, Payment Information, etc. Paragraphs to provide more information to the user. Tables for rendering pricing information or something else.

So having the ability to add custom properties to a custom section on the form will help us to create build complex forms without the need to create a DB field just to display rich text.

Additionally, we could define form layouts more easily and structured. If we are using a CSS framework such as Bootstrap, we can define a custom form property in a form section and set the grid system or panels to use and then just create one custom form section controller rather that 1 per every grid system option.

### Proposed solution

Maybe, by creating custom attributes to the controller, so we can set which FormComponents to display on a specific Form section and store this information on the Form Builder Layout. The Form section custom properties are being displayed on the right column one it is selected. Add a color to the section selected to we bring clarity to the user which form section they are editing.

`
"sections": [
        {
          "identifier": "960e4557-ac11-4256-9d6d-b74afb724e0c",
          "type": "Custom.Form.Section",
          "formComponents":[
            {
                  "identifier": "1d2e92f1-5353-4509-8779-0ca15a6a2fb9"
            },
           {
                  "identifier": "1d2e92f1-5353-4509-8779-0ca15a6a2fb9"
            }
           ],
          "zones": [
            {
              "identifier": "1bffe99d-cb5a-46dc-9a70-32b1c7c5aea0",
              "formComponents": [
                {
                  "identifier": "1d2e92f1-5353-4509-8779-0ca15a6a2fb9"
                }
              ]
            }
          ]
        },
`

Then on the Partial View we can maybe automatically use **@ViewData["CustomPropertyName"]**

Note: This is just an idea, since I don't know the Kentico source code.

### Additional context

Sample of a form:
![image](https://user-images.githubusercontent.com/1047398/79777977-a5e7f380-82fd-11ea-9bd2-74f862d605aa.png)

Sample of all potential layouts we can implement once we get enabled custom properties on Form Sections:
![image](https://user-images.githubusercontent.com/1047398/79778066-cb74fd00-82fd-11ea-8bd1-11e39efb1f1e.png)

**Comment by OndraM-Kentico** [comment]
Thank you for you suggestion! As this is not directly related to the components repository, I have forwarded this to the product team and it has already been sumitted as a feedback to our ProductBoard. Stay tuned as the public product portal is available later this year.

**Comment by OndraM-Kentico** [comment]
I'm closing it for now but I you wanted to add more info later, don't hesitate to open a new issue a link it with this one.

**Comment by vhugogarcia** [comment]
Thanks @OndraM-Kentico for being in contact with me on this. If there is any question or anything I can help with, please let me know! 

Also, I would like to know which is the link from the public portal or beta releases notes, so I can see  the progress of these requests, please.

**Comment by Simply007** [comment]
Just adding the productboard link for future reference:
* https://portal.productboard.com/kenticoxperience

**Comment by vhugogarcia** [comment]
Thanks @Simply007 

I added them to the product backlog you posted above as ideas, but they were deleted without any notificacion or comment 😔

So, I do not know the status of them.

**Comment by Simply007** [comment]
@vhugogarcia - There might have been some misunderstanding.

When you submit the idea to the Product Board, it does not get immediately visible. The ideas are stored in the system, they are groomed, merged/split, prioritized, basically processed to be ready to be put into the backlog. 

Then, when the feature is marked as "under consideration", it became visible on the product board, so don't worry I believe the idea/feature request hasn't been, it is being prioritized against other features opportunities.

**Comment by vhugogarcia** [comment]
That is good to know @Simply007 . Thanks for bring clarity to the process! I will keep an eye on it  then 👍
