### ISSUE TITLE
[Proposal] Nested Form Sections

### ISSUE THREAD

**Issue by vhugogarcia** [Kentico/ems-mvc-components#120]
### Motivation

Multi-step forms

### Proposed solution

Add the ability to add nested Form Sections. Example:

    <fieldset>
        <div class="form-row">
            <div class="col-7">
                <input type="text" class="form-control" placeholder="City">
            </div>
            <div class="col">
                <input type="text" class="form-control" placeholder="State">
            </div>
            <div class="col">
                <input type="text" class="form-control" placeholder="Zip">
            </div>
        </div>
        <div class="form-row">
            <div class="col">
                <input type="button" name="next" class="next action-button" value="Next" />
            </div>
        </div>
    </fieldset>
    <fieldset>
        <div class="form-row">
            <div class="col-7">
                <input type="text" class="form-control" placeholder="City">
            </div>
            <div class="col">
                <input type="text" class="form-control" placeholder="State">
            </div>
            <div class="col">
                <input type="text" class="form-control" placeholder="Zip">
            </div>
        </div>
        <div class="form-row">
            <div class="col">
                <input type="button" name="next" class="next action-button" value="Next" />
            </div>
        </div>
    </fieldset>

### Additional context

By having the ability to nest form sections, we can create multi-steps form layouts without hacks or workarounds that make complex the maintenance. 

This would be a great companion for my other proposal which are the custom form section properties.

**Comment by OndraM-Kentico** [comment]
Thank you for you suggestion! As this is not directly related to the components repository, I have forwarded this to the product team and it has already been sumitted as a feedback to our ProductBoard. Stay tuned as the public product portal is available later this year.

**Comment by OndraM-Kentico** [comment]
I'm closing it for now but I you wanted to add more info later, don't hesitate to open a new issue a link it with this one.

**Comment by vhugogarcia** [comment]
Thanks @OndraM-Kentico for being in contact with me on this. If there is any question or anything I can help with, please let me know!

Also, I would like to know which is the link from the public portal or beta releases notes, so I can see the progress of these requests, please.

**Comment by Simply007** [comment]
Just adding the productboard link for future reference:
* https://portal.productboard.com/kenticoxperience
