### ISSUE TITLE
What is the format for inserting Dynamic Text into the editor text

### ISSUE THREAD

**Issue by dom3551** [Kentico/ems-mvc-components#121]
Hi, 

From reviewing the code, I see that the RichText widget supports some dynamic text substitution, such as ContactFirstName and ContactLastName. However, from the Regex expressions I cannot work out what the format of the text needs to be for the substitution to occur....please could you confirm what I must place in the text to get the ContactFirstName showing for example......I appreciate that the Enterprise marketing module must also be turned on.

Currently the classes/methods to add substitution patterns and their functions are internal to the class.....is there a reason why you didn't make these public so we can add our own patterns and functions in our project? Would it be possible to make these public so we can?!

Thanks

**Comment by petrinecp** [comment]
Hi @dom3551, You're right, the RichText widget does support dynamic text substitution feature and it can be accessed from the toolbar:
![image](https://user-images.githubusercontent.com/5637849/80953073-18c39500-8dfb-11ea-8e25-6d1e3bf70a48.png)

You can either choose to resolve the dynamic text's value from URL parameter or from the current contact attributes.

For now the dynamic text pattern register is internal, however this could change in the future, but for now if you're willing to build the component from the source files you can register additional patterns in the `DynamicTextPatternRegister.PopulatePatterns` method.
