### ISSUE TITLE
Support for lowercase URLs in rich text editor

### ISSUE THREAD

**Issue by ynzenu** [Kentico/ems-mvc-components#130]
### Motivation

For SEO purposes it is sometimes preferred to use only lowercase characters in URLs throughout the site. Using a couple of techniques this is possible in most places but not in the rich text editor. I believe that allowing the developer to configure the URLs to be rendered in lowercase could be a good addition. 

### Proposed solution

In MVC you can set this variable `RouteTable.Routes.LowercaseUrls` for routing. Setting it to true will cause any MVC API methods to convert URLs to lowercase. Potentially this variable can be checked when rendering URLs in the rich text editor.

### Additional context

A workaround for this is to create a method similar to the existing `ResolveUrls` and use it to convert URLs to lowercase. The method can then be used to parse the property value that is used for the rich text.

**Comment by davidkomarek** [comment]
Hi Atzie, thanks for your suggestion! Based on the input from our development team, this should be handled system-wide in Kentico Xperience and I am therefore adding this as a feature request to our ProductBoard.
