### ISSUE TITLE
Link Styles are not available

### ISSUE THREAD

**Issue by spitzfaust** [Kentico/ems-mvc-components#132]
### Brief bug description

First of all: Thank you for the great richtext editor integration. It is very extendable and customizable. 
We tried to define custom link styles as described in the Froala documentation (https://froala.com/wysiwyg-editor/examples/link-styles/) and the button to select those styles is simply not showing up when clicking into a link. Other custom configurations and custom plugins are working as expected.

### Repro steps

1. Add `linkStyles` to the richtext default configuration.
2. In the richtext widget insert a link.
3. Klick on the link in the text and a pop-up menu with "open", "edit", and "unlink" appears.

### Expected behavior

Inside of the pop-up menu a "style" selection should be visible where the configured styles can be selected.

### Test environment

 - Browser Chrome, Firefox, Edge (old and new)
 - Version Kentico.EMS12.MvcComponents.Widget.RichText 1.2.1

**Comment by petrinecp** [comment]
Hi @spitzfaust,

in our default configuration we removed the `'linkStyle'` button from the [linkEditButtons](https://froala.com/wysiwyg-editor/docs/options#linkEditButtons) option, therefore, to make the button visible again, please also provide a `linkEditButtons` option in your custom toolbar configuration and add back the `'linnkStyle'` button like so:

```
{
  ...
  linkEditButtons: ['linkOpen', 'linkStyle', 'linkEdit', 'linkRemove'],
  linkStyles: { /* Your link styles */ },
  ...
}
```

**Comment by spitzfaust** [comment]
Thank you this worked like a charm :+1:
