### ISSUE TITLE
Can't load widget view

### ISSUE THREAD

**Issue by JBratteli** [Kentico/ems-mvc-components#141]
### Brief bug description

I chose the bug template, but I think there's a good chance this is an error on my part. I have been using the Rich Text Widget from the NuGet package on my site. I received new requirements to add a couple options to the widget configuration. I can’t do that with the package, so I removed the package and downloaded the source, but I can't get it to run after I build it.

### Repro steps

1. Download v1.2.1-richtext.
2. Copy files into my solution directory.
3. Build Kentico.Components.sln
4. In my project, add references to the just-built Kentico.InlineEditor.RichText.dll,Kentico.Widget.RichText.dll, and Kentico.Widget.RichText.Views.dll
5. Build my project.
6. View a page with a previously existing Rich Text widget on it.
7. Get an exception (stack trace below)

I attempted to create a new page to test if a new instance of the widget would work, but I can't create a page; I get the same exception.

### Expected behavior

Rich Text widgets should work as they did with the package installed.

### Test environment

Kentico Xperience 12.0.90 MVC

### Additional context

Exception information: 
    Exception type: InvalidOperationException 
    Exception message: Embedded view type was not found for view path '~/Views/Shared/Kentico/Widgets/_RichTextWidget.cshtml'.
   at Kentico.Web.Mvc.EmbeddedViewLoader.LoadMappingTable()
   at Kentico.Web.Mvc.EmbeddedViewMapping.LoadMappping()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Kentico.Web.Mvc.EmbeddedViewBootstrapper.EmbeddedViewModuleInitializer.Init(HttpApplication context)
   at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
   at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
   at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
   at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)

**Comment by petrinecp** [comment]
Hi @JBratteli, sorry for the delayed response, I've just tested the rich text widget built from the source files on the same instance v12.0.90 and had no issues.

This is what i did:
1. Downloaded and extracted this repository
2. Open the solution in VS and build it
3. Open the solution folder in powershell and run `npm run i` and then `npm run build`
4. Go into the `~\SandboxSite\bin` folder and copy the `Kentico.InlineEditor.RichText.dll`, `Kentico.Widget.RichText.dll` and `Kentico.Widget.RichText.Views.dll` into my **MVC site project**'s bin folder
5. Go to `~\SanboxSite\App_Data\Global\Resources` and copy `Kentico.InlineEditor.RichText.resx` and `Kentico.Widget.RichText.resx` to the same path in the MVC project `~\MyMvcSite\App_Data\Global\Resources`
6. Copy the content files from `~\Kentico.InlineEditor.RichText\Content` and `~\Kentico.Widget.RichText\Content` to the corresponding content folder in my MVC project `~\MyMvcSite\Content`

**Comment by JBratteli** [comment]
I got it working, thank you.
