### ISSUE TITLE
Errors and unexpected dependencies when adding widget projects to custom solution

### ISSUE THREAD

**Issue by yuriys-kentico** [Kentico/ems-mvc-components#19]
### Brief bug description

I tried to use the files in this repository. While it is a work-in-progress, I was not able to get it to work in a custom project's page builder.

### Repro steps

1. Start with a Framework 4.6.1 MVC project configured for Page Builder connected to a 12.0.31 admin. Custom widgets defined in this project work.
1. Clone this repository in a separate location.
1. Copy the `Kentico.Widget.RichText` and `Kentico.Widget.RichText.Views` projects over (their folders and contents).
1. In VS2019, add these existing projects.
1. Run into error 1.
1. Copy the _Targets_ folder over as well.
1. Add the projects successfully.
1. Build the solution.
1. Run into error 2.
1. Also add `Kentico.InlineEditor.RichText` since it contains the dependency.
1. In the main application project, reference the 3 new projects.
1. Rebuild the solution.
1. Open admin to **Pages** and select a page using page builder.
1. Run into error 3.
1. Dereference the `Kentico.Widget.RichText` projects.
1. Copy, add and reference the `Kentico.Widget.Video` projects.
1. Rebuild and reload admin, run into the same error 3.
1. After a build, a folder called _SandboxSite_ is created. This contains a _bin_ folder with DLLs and PDBs for the widget projects, as well as _App_Data\Global\Resources_ with RESX files for the widgets.
1. Copy those files into the real MVC project folder.
1. Reload admin.
1. Run into error 4.

### Actual results

Error 1:
![EmsMvcComponentsError1](https://user-images.githubusercontent.com/34716163/62782968-59b79480-ba89-11e9-97e9-031a0fcd5ff3.png)

Error 2:
![EmsMvcComponentsError2](https://user-images.githubusercontent.com/34716163/62784173-de0b1700-ba8b-11e9-939c-fe7a0123683d.png)

Error 3:
![EmsMvcComponentsError3](https://user-images.githubusercontent.com/34716163/62784779-427aa600-ba8d-11e9-89aa-1db943f852a5.png)

Error 4:
![EmsMvcComponentsError4](https://user-images.githubusercontent.com/34716163/62785499-bff2e600-ba8e-11e9-9983-32980be01b55.png)

### Expected behavior

- No requirement to add the _Targets_ folder, or the need for it added to installation steps.
- No dependency in an "unrelated" project, or the need for it added to installation steps.
- Views should be found and widget available for use in page builder.

**Comment by rpribyl** [comment]
There were incomplete installation instructions for the Video widget.

We've updated them here:
https://github.com/Kentico/ems-mvc-components/pull/14

The main difference is that we expect that the repository will be built first and only the component assets will then be copied into the MVC application.

**Comment by yuriys-kentico** [comment]
Thanks Radek! If that is the case, why does it say in [the repository README](https://github.com/Kentico/ems-mvc-components/blob/master/README.md) that:
> This repository contains page builder components, which can be used and modified in your projects.

If the components are precompiled, how would they be modified? Would I build a separate solution and copy over assets every time I make a change?

**Comment by rpribyl** [comment]
Hi Yuriy,
These current components (Rich text + Video) in this repo are going to be distributed via NuGet packages and would not provide customization of the markup.
We are about to introduce a customization option for the Rich text editor though.

Customers are advised to copy the build assets into their projects just to make it easier to use until we have the NuGet packages available.
They are still able to copy the components' projects manually into their solutions however we do not provide any help or steps here.

I've removed the misleading path of the sentence you've mentioned.

**Comment by OndraM-Kentico** [comment]
Hi @yuriys-kentico, has anything left to solve the issue?
