### ISSUE TITLE
Installation instructions missing some details

### ISSUE THREAD

**Issue by phixxo** [Kentico/ems-mvc-components#29]
### Brief bug description

Following the install steps leads to an error saying that the widget has been already registered and that the registration of the inline editor XYZ failed. 

### Repro steps

I have just followed the install steps to the point. Together with LadislavM :-)
https://www.screencast.com/t/gOBAh35W6uLs 

### Expected behavior

Working richt text editor widget which can be placed on the page. 

### Test environment

Occurs in FireFox, Chrome. Kentico 12.0.40, sample Dancing Goat MVC project.

**Comment by rcskpeters2** [comment]
I had sent this issue to support and I see the changes to the readme, but there is one part that still doesn't make sense. In the readme, it refers to Content folders, Kentico.Widget.RichText/Content, but that folder does not exist in the repos.

**Comment by KenticoPavelV** [comment]
> I had sent this issue to support and I see the changes to the readme, but there is one part that still doesn't make sense. In the readme, it refers to Content folders, Kentico.Widget.RichText/Content, but that folder does not exist in the repos.

'npm run build` command (step 4) generates these Content folders.
