### ISSUE TITLE
Froala License

### ISSUE THREAD

**Issue by rcskpeters2** [Kentico/ems-mvc-components#34]
### Brief bug description

When migrating the widget I am getting a license error with Froala.

### Repro steps

I integrated the component on my developer machine and it works great!
I checked everything into our private git repo
Moved to the dev server and pulled down the branch
Everything is working on the dev server, but I am receiving a Froala license issue saying it is unlicensed. 

### Expected behavior
Based on the readme, this widget should come with a license for the Froala component.

### Additional context

Is there a specific file that needs to be migrated for the license? I am not sure if it could be ignore from the .gitignore file.

**Comment by OndraM-Kentico** [comment]
My apologies for the late reply... First off, please ensure that you have installed Kentico hotfix 12.0.38 on your machine.

**Comment by OndraM-Kentico** [comment]
@rcskpeters2, please let me know whether you have managed to solved it by applying the mentioned hotfix.

**Comment by rcskpeters2** [comment]
Yes, I ended up applying the latest hotfix for 12.0.43 and it resolved the
issue.

Thanks!

**Comment by OndraM-Kentico** [comment]
Glad to hear that. Thanks
