### ISSUE TITLE
Ability to Configure Editor without compiling everything

### ISSUE THREAD

**Issue by KenticoDevTrev** [Kentico/ems-mvc-components#38]
### Motivation

Currently in order to modify the rich text editor, you need to have the entire solution and build it, and it compiles into a minified .js file.  It's near impossible to do small adjustments for clients with this, and very hard to also package this into a nuget package.

### Proposed solution

Move configuration into a .js that isn't compiled and can be added to solutions and modified without requiring rebuilding.

**Comment by OndraM-Kentico** [comment]
Thank you for the suggestion, I agree that it's painful to proceed the whole process because of the small adjustment. We plan to introduce a model of Froala rich text editor customization as well as introducing components as NuGet packages which could help a bit. @KenticoDevTrev, could you please name kinds of the adjustments you typically do?

**Comment by KenticoDevTrev** [comment]
Biggest adjustment is the tools available on the toolbar, portal had the different profiles that we could set for the user, that covered the majority of what we did (usually using full or basic most times).

Making an API or method that generates the froala initialization options json would probably do the trick, then allow us to modify those profiles (even just modifying the json itself would work).

**Comment by OndraM-Kentico** [comment]
I've got good news for you. In the current iteration we're implementing a support for adjustments of the Rich text editor. Once done, you'll be able to define custom toolbar and customize other Froala's options.

**Comment by KenticoDevTrev** [comment]
Awesome!!! I'll tell the team, they will be super excited!

**Comment by KenticoDevTrev** [comment]
@petrinecp  I saw it was merged in, is there any documentation on how to leverage the new adjustments? :)

**Comment by petrinecp** [comment]
Hi @KenticoDevTrev, the documentation will soon be available on the repo's wiki page, however we're also finishing the support for custom plugins and there will be a minor change in the current location of the configurations so bear with us. :)

**Comment by rpribyl** [comment]
Hi @KenticoDevTrev, the implementation of the Editor customization is finished. You can find the documentation [here](https://github.com/Kentico/ems-mvc-components/wiki/Customizing-the-Rich-text-editor-toolbar).
Could you please check that it covered all your needs?

P.S.: We are just finishing a release of the Rich Text Editor via a NuGet package :)

**Comment by KenticoDevTrev** [comment]
Perfect, this will do nicely and cover the vast majority of used, please
get this into a nuget package as soon as you can and we will start
incorporating it!!

**Comment by KenticoDevTrev** [comment]
Could you add a link to the documentation on the readme (in case people don't realize the wiki is there) and also add the missing @using statement for the instructions on adding as a inline editor for your widgets?

``` csharp
@using Kentico.PageBuilder.Web.Mvc
@using Kentico.Components.Web.Mvc.InlineEditors

@{Html.Kentico().RichTextEditor("Content", "simple");}
```

**Comment by rpribyl** [comment]
Thank you for the suggestions, all done now :)
