### ISSUE TITLE
Page Selector for linking text to pages within Kentico CMS

### ISSUE THREAD

**Issue by LewisParkinson** [Kentico/ems-mvc-components#44]
This would make it much easier for the user to link some text to a page on the site and not have to worry about going through each page that link to a certain page after that page alias path is changed, for any reason.

This is used within the CK editor within the CMS so could use similar functionality as this.

**Comment by OndraM-Kentico** [comment]
Hello, #48 introduced the ability to link pages from the content tree.

**Comment by LewisParkinson** [comment]
Hi @OndraM-Kentico,

Thanks for letting me know.
I have implemented these changes into my project and looks good. 

Do you know if it's possible to have the text box option as well (like the 'imageLink' option currently has), or would it need to be a separate option in the tool bar? Would make it a bit more flexible if the user would like to link text, or an image, to an external link or page within the content tree.

Still not 100% sure where everything is yet. I've been looking through the JavaScript (main.js) and can't see how this was working before compared to how it's working now.

**Comment by OndraM-Kentico** [comment]
I see your point and I can spoil that we will introduce 'insert external link' functionality in the near future. Unfortunately, at this moment the master branch is in "temporary" state where Froala's built-in plugin was replaced with the ours while the new tab allowing to insert external links was not implemented yet.

**Comment by LewisParkinson** [comment]
Okay, thanks @OndraM-Kentico
