### ISSUE TITLE
Link selector dialog partially obscured in small section.

### ISSUE THREAD

**Issue by CompDr** [Kentico/ems-mvc-components#49]
### Brief bug description

When opening Link dialog most of it is hidden when the section it is contained in is smaller than the dialog box

### Repro steps

1. Open the link dialog in an otherwise empty section.

### Expected behavior

What the correct behavior is?

Dialog would be completely visible.

### Test environment

 - Browser chrome
 - Version 77.0.3865.120 (Official Build) (64-bit)

### Screenshots

Add links to screenshots, if possible.
![image](https://user-images.githubusercontent.com/4969761/67224556-12d60b80-f3f7-11e9-804f-6c465bc21aff.png)

**Comment by OndraM-Kentico** [comment]
Hi, thank you for reporting. I've already addressed this design issue and the fix can be expected in the near future.

**Comment by petrinecp** [comment]
This should be now fixed by #65.
