### ISSUE TITLE
Missing routeConfig step in readme

### ISSUE THREAD

**Issue by CompDr** [Kentico/ems-mvc-components#50]
### Brief bug description

What went wrong?
The readme was missing a step to allow the RichTextInline editor to work.

### Expected behavior

Readme has a step like:
 Call `routes.Kentico().MapRichTextInlineEditorRoutes();` where `routes` is your site's RouteCollection.

**Comment by rpribyl** [comment]
Hello,
Thank you for your feedback.

Your suggestions have been added to the readme file: https://github.com/Kentico/ems-mvc-components/pull/51
