### ISSUE TITLE
New page selector functionality removed the ability to add external links or named anchors

### ISSUE THREAD

**Issue by CompDr** [Kentico/ems-mvc-components#52]
### Brief bug description
Lost ability to manage external links when page selector functionality replaced froala's built in link editor.

### Repro steps

1. Click on link editor
2. Click on only button in sub menu
3. That button opens a modal that only allows selecting links to pages within Kentico

### Expected behavior

What the correct behavior is?
Have the ability to add/edit links to external urls and be able to add named anchors to any internal or external url.

### Test environment
 - Browser Chrome
 - Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by OndraM-Kentico** [comment]
Hi, it's a known issue to us, we've already discussed it in #44. 
> I see your point and I can spoil that we will introduce 'insert external link' functionality in the near future. Unfortunately, at this moment the master branch is in "temporary" state where Froala's built-in plugin was replaced with the ours while the new tab allowing to insert external links was not implemented yet.

**Comment by petrinecp** [comment]
#60 was just merged to master which add addresses this issue.
