### ISSUE TITLE
Missing closing tag on inline editor.

### ISSUE THREAD

**Issue by thejocus** [Kentico/ems-mvc-components#59]
### Brief bug description

The inline editor produces erroneous HTML, because of the HtmlHelperExtension method RichTextEditor is using the TagRenderMode.SelfClosing on a div.

### Repro steps

Use the inline editor, inspect the HTML, you'll notice that you're tags are incorrectly nested.

### Expected behavior

All tags with appropriate closing tags.

### Proposed fix
Instead of using the TagRenderMode.SelfClosing option change to use a new HtmlString.
`htmlHelper.ViewContext.Writer.Write(new HtmlString(tagBuilder.ToString()));`

I have confirmed that this works for me, but it's worth further testing.

**Comment by OndraM-Kentico** [comment]
Thank you for reporting this. However, I can't imagine a situation when it actually bothers you. Could you please describe one? You're right that widget markup contains inline editor's wrapper in a form of self-closing tag. Nevertheless, Javascript then modifies its sub-tree to render an inline editor so the self-closing tag should appear only a while.

**Comment by thejocus** [comment]
In my case, I was using 2 of the inline rich text editors in a single widget. They were each in their own column. (2-column layout) but because of the erroneous HTML, it broke my layout as the divs were not closed as expected.
