### ISSUE TITLE
Rich Text Form Component, Dialogue Rich Text Editor

### ISSUE THREAD

**Issue by KenticoDevTrev** [Kentico/ems-mvc-components#79]
### Motivation

The Rich Text editor could use a couple more pieces so we don't need to manually create them (having to do that now).  First this tool should be usable as a Form Component for widgets and Online Forms.

Second there should be both the Inline Rich Text Editor, and a Widget Dialogue version, as many times the area where the rich text should go isn't large enough to accommodate the Froala interfaces easily.

### Proposed solution

I'll post my code once done so you can incorporate

**Comment by KenticoDevTrev** [comment]
Sadly i couldn't get an Inline Form Component going, i called Html.Kentico().RichTextEditor("Html", "default"); from my FormComponent View for the Html property, but it wouldn't render in the widget dialog, no errors or anything, so something must be going on with the events.

**Comment by petrinecp** [comment]
The `Html.Kentico().RichTextEditor` method utilizes the `Html.Kentico().BeginInlineEditor` API which only work on the page directly, in order for the RTE to work in widget properties dialog, a form component with custom JS initialization is needed.

**Comment by KenticoDevTrev** [comment]
Definitely going to need widget dialog capabilities, hopefully the enhancement won't take too long, otherwise I may need to load the tiny mce editor temporarily for widget dialog.

**Comment by davidkomarek** [comment]
Hi Trevor, thanks for the suggestion and your effort to make the enhancement. Unfortunately, this enhancement is currently not at the top of the backlog. It would be very helpful if you could share your most common scenarios for such enhacement.

**Comment by KenticoDevTrev** [comment]
To create the widley issue rich text widget for page builder as one primary
case. Often an area may be too small to fit awysiwig (such as a 2 column
bootstrap), having a rich text in a modal dialogue is a life saver for
that.  Also say for a widget that can contain html (maybe A map widget with
pin that you click to see info) you can't always put a wysiwyg editor where
you need the rich text.

I'll install the tiny mce to compensate, sucks for now : /

**Comment by KenticoDevTrev** [comment]
We've gotten some feedback from some of the other Kentico MVPs (4 including me, haven't heard from the rest) and they agree that having a form component of this is a must, any way to get this higher priority?

@davidkomarek  can pass along the Slack conversations and notes we provided on scenarios and need.

**Comment by KenticoDevTrev** [comment]
Any news on this? I heard it was part way about a month ago.  I see it's set to "Waiting" but do we have any indication on when/if it will be out?

**Comment by davidkomarek** [comment]
Hello Trevor, we came up with several solutions and have mockups ready review. You can expect a PM shortly.
The story is still subject to groomings and therefore there is no fixed release date set.

**Comment by vhugogarcia** [comment]
Hello @KenticoDevTrev , I am trying to use an WYSIWYG on the TextAreaComponent, were you able to implement it? and if yes, how?

Also @davidkomarek one little tiny feature that would be super helpful would be the ability to add custom properties to the Form Sections.

**Comment by vhugogarcia** [comment]
I made it work @davidkomarek.

After some JS, CSS, I was able to manage the injection of an WYSIWYG form component property.

![image](https://user-images.githubusercontent.com/1047398/79150725-daecc700-7d8e-11ea-9f52-bcc38e0a650e.png)

**Comment by davidkomarek** [comment]
Hello @vhugogarcia thanks for suggestions! Can you share some of the scenarios for properties on form sections and the wysiwyg? Thanks!

**Comment by KenticoDevTrev** [comment]
@davidkomarek , @vhugogarcia  can speak for his items, but i will say we have used the rich text editor in the Form tab for things such as:

Description areas for elements (needing links, bulleted lists, bold texted areas)

Sometimes basic tables for things like pricing listings in a section of text.

@vhugogarcia  are you saying though you got Froala working on the form tab with your screen shot? I know others complained that right now they have to customize CKEditor for admin side and froala for mvc side.

**Comment by vhugogarcia** [comment]
> Hello @vhugogarcia thanks for suggestions! Can you share some of the scenarios for properties on form sections and the wysiwyg? Thanks!

Thanks for asking. As @KenticoDevTrev mentioned it. Not all forms are just a simple array of fields. Complex forms requiere the ability to add Headings to outline a section of the form, for example: Billing Informacion, Payment Information, etc. Paragraphs to provide more information to the user. Tables for rendering pricing information or something else. 

So having the ability to add a custom property to a custom section on the form will help us to create build complex forms without the need to create a DB field just to display rich text. Also it will be ideal from you to add a FormComponent RichTextBox so we can add them to the custom form section and then the user can edit the text of the form from the form builder page, just like I showed in the screenshot above. The screenshot above is basically doing that, but I had to create a form component that I add into a section so I can add Headings and so on. The bad thing about that is the it creates a DB field in SQL, which does not appear the be the best practice, but sadly we are limited right now on Kentico. 

Let me know if there is anything else I can help with.

**Comment by vhugogarcia** [comment]
> @vhugogarcia are you saying though you got Froala working on the form tab with your screen shot? I know others complained that right now they have to customize CKEditor for admin side and froala for mvc side.

I just implemented Summernote (A Simple WYSIWYG) into a Form component property for a "Textarea".  Basically, since the form I'm building requires to add some headings, paragraphs, etc, I created a Form Component named: "ContentFormComponent" then I add a custom property for this and then by using JS I inject the WYSIWYG editor into the text area field for that specific component. Based on Kentico documentation we can use the .admin.css and .admin.js to inject styles and scripts into the form builder area, which is basically what I am doing. Again, not ideal, due to the "ContentFormComponent" creates a DB field (null) but at least it works, until Kentico team implements Form Sections custom properties an rich text component property.

**Comment by vhugogarcia** [comment]
@davidkomarek Another AWESOME thing we can do if we could get Form Section properties will be to define form layouts. 

So, for example, if we are using a CSS framework such as Bootstrap, we can define a custom form property in a section and set the grid system to use and then just create one custom form section controller rather that 1 per every grid system option.

**Comment by KenticoDevTrev** [comment]
I've asked for that as well, I can't make a bootstrap layout form section
without properties.

**Comment by OndraM-Kentico** [comment]
FYI, rich text Nuget package v1.3.0 has just been released -- it delivers Rich text form component you demanded. Please, try it out and let us know if we can close this issue 😉

**Comment by KenticoDevTrev** [comment]
Sweet!!! I'll give it a shot right away!

**Comment by KenticoDevTrev** [comment]
It's working awesomely, the only last request now is for the ability to add the Configuration property to the RichTextProperties and wire it up, that way we can specify what type of configuration toolset we want for the widget (ex a "Basic" one with only a couple elements vs. a full one)

**Comment by petrinecp** [comment]
Hi @KenticoDevTrev, we've integrated the rich text widget directly into the Kentico Xperience 13 together with the form component property for specifying a custom configuration, however we won't be backporting it to the v12 version. If you need it in Kentico 12, you'll have to download the source files and add it yourself, which should be pretty straightforward. 🙂

**Comment by KenticoDevTrev** [comment]
Thanks! I'll see about back porting, may just leave it as is possibly
unless a client needs it, I'll have enough work to do to update my existing
modules for 13!
