### ISSUE TITLE
Assembly Registration Error

### ISSUE THREAD

**Issue by InetJustin** [Kentico/ems-mvc-components#86]
After installing this NuGet package and attempting to load the administration application I receive the following error:

**Additional assemblies have to be registered before application pre-initialization.**

Line 16: #endif
Line 17:         // Initialize CMS application. This method should not be called from custom code.
Line 18:         InitApplication(Assembly.GetExecutingAssembly());
Line 19:     }
Line 20: }

Any advice on how to fix this or why it is happening? Everything compiles just fine but then doesn't execute properly. This is on version 12.0.52 of Kentico 12 MVC.

**Comment by petrinecp** [comment]
Hello @InetJustin, the NuGet package is meant for installation in the MVC project, did you install it there or in the administration?

**Comment by InetJustin** [comment]
Whoops! Yes I installed it in the Administation application not the MVC application, thank you!!
