### ISSUE TITLE
Add ability to the link tool bar item to pick a media link in addition to page and custom

### ISSUE THREAD

**Issue by nwbowensby** [Kentico/ems-mvc-components#90]
### Motivation

We'd like to be able to link to a document or image in the media library for people to download (most likely a document).  Right now this can only be done with a custom link and that requires more time and effort on the editor.

### Proposed solution

The popup for inserting a link has 2 "tabs" currently.  One for a page link and one for a custom link.  You could add a third option to use the media picker used for inserting an image to instead create a link to it.

**Comment by rpribyl** [comment]
Hi @nwbowensby,
there is already a [pull request (88)](https://github.com/Kentico/ems-mvc-components/pull/88) that adds this functionality. It will add another "Media" tab that will allow inserting a link from a media library.
It's being tested at the moment.

Once it's tested and closed and also the other [pull request (89)](https://github.com/Kentico/ems-mvc-components/pull/89) is closed you can expect a Rich text NuGet package update with these two features.

**Comment by nwbowensby** [comment]
Thank you for the response.  Do you think this may be ready by next week or could this take longer to get through the process?  Just trying to determine if I need to come up with something in the interim to get our web team over a hump while we wait for the new feature.  They have a lot of documents to link and were wanting this to save them a lot of time.  We are also on a bit of a time line to get our site moved to Kentico.   I do not expect you to rush things....just wanting to get expectations so I can report back and and see if I need to come up with a temporary workaround or not.

**Comment by rpribyl** [comment]
Hi @nwbowensby,
We are planning to release the two features (together with another bug fix) during the next week.

**Comment by nwbowensby** [comment]
I'd like to reopen this ticket as your update did not resolve this as promised.  They key thing I mentioned in the description of this request is document.  From my testing and the testing of our content admin you cannot pick a document for the link from within the link control.  If this is a setting we need to set somewhere please let me know.

**Comment by rpribyl** [comment]
Hi @nwbowensby,
We've decided to reopen this issue (as suggested) since the implementation of the "insert media link" feature should not check the 'imageAllowedTypes' configuration at all (mentioned as a workaround in [#90](https://github.com/Kentico/ems-mvc-components/issues/95)).
We'll remove the check so that all files that can be uploaded into a media library can be linked.

**Comment by petrinecp** [comment]
Hi @nwbowensby, we've release v1.2.0 which fixes the restriction on file types when inserting media links, therefore the customization suggested in https://github.com/Kentico/ems-mvc-components/issues/95#issuecomment-579125966 is no longer needed and should not be used for this scenario. This option is now only respected when inserting images into the editor.
