### ISSUE TITLE
Revisit/Reopen #90 - Creating link to document

### ISSUE THREAD

**Issue by nwbowensby** [Kentico/ems-mvc-components#95]
### Motivation

Why is this feature required? What problems does it solve?

If you reread #90 you will see that I requested to be able to create a link to a document in the media library. I tested your new release and you cant do this even though you closed the ticket.  The issue is that the popup for selecting media has a restriction on it to limit it to pictures.  I need to use it for pdfs.  If there is a setting to control this please let me know

### Proposed solution

An ideal solution for the above problems.

### Additional context

Add any other context, screenshots, or reference links about the feature request here.

**Comment by OndraM-Kentico** [comment]
I'm sorry about the misunderstanding. At the time you wrote the original issue, it was not possible to create a link to a media file at all. We had to introduce the functionality first. Allowing specific file types is a matter of configuration. PDFs are not allowed file types by default, however you can allow them using a custom configuration, see https://github.com/Kentico/ems-mvc-components/wiki/Customizing-the-Rich-text-editor-toolbar. The code may look like this:
```
<script>
    (function (pageBuilder) {
        var richTextEditor = pageBuilder.richTextEditor = pageBuilder.richTextEditor || {};
        var configurations = richTextEditor.configurations = richTextEditor.configurations || {};
        // This would override the default configuration
        configurations["default"] = {
            imageAllowedTypes: ['jpeg', 'pdf'],
        };
    })(window.kentico.pageBuilder);
</script>
```

**Comment by nwbowensby** [comment]
Thank you for the information.  The reason I put that ticket in was because the media functionality wasn't there so I was well aware of that.  I was a little disappointed that my ticket was closed before I was given a chance to verify it would be taken care of.  I'm glad that it all worked out though.
